// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.Entities;

namespace MyProject.Migrations
{
    [DbContext(typeof(MyProjectContext))]
    [Migration("20220118152139_AddedArticles")]
    partial class AddedArticles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyProject.Entities.Article", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Article_Size")
                        .HasColumnType("int");

                    b.Property<string>("Article_Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PageID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("MyProject.Entities.Page", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("MyProject.Entities.Article", b =>
                {
                    b.HasOne("MyProject.Entities.Page", "Page")
                        .WithMany("Articles")
                        .HasForeignKey("PageID");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("MyProject.Entities.Page", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
